parameters:
    app.path.spots:  /uploads/spots
vich_uploader:
    db_driver: orm

    mappings:
        spot_images:
            uri_prefix:  '%app.path.spots%'
            upload_destination:  '%kernel.project_dir%/public/uploads/spots'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
